In [2]:
import numpy as np 

In [3]:
arr = np.array([1,23.45,'demon',11+11j])
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['1', '23.45', 'demon', '(11+11j)'], dtype='<U64')

In [4]:
li=[1,2,3]
arr=np.array(li,dtype=float)
arr

array([1., 2., 3.])

In [5]:
li=[1,2,3]
arr=np.array(li,dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [6]:
li=[1.5,2.5,3.5]
arr=np.array(li,dtype=int)
arr

array([1, 2, 3])

In [7]:
li=[1.5,2.5,3.5]
arr=np.array(li,dtype=complex)
arr

array([1.5+0.j, 2.5+0.j, 3.5+0.j])

In [8]:
arr=np.array(100)
print("Array:",arr)
print("Dimension of Array:",arr.ndim)

Array: 100
Dimension of Array: 0


In [9]:
arr=np.array([1,2])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("dimension:",arr.shape)

Array: [1 2]
Dimension of Array: 1
dimension: (2,)


In [10]:
arr=np.array([[1,2,3,4,5,6,7,8,9,10],
            [10,20,30,40,50,60,70,80,90,100],
            [100,200,300,400,500,600,700,800,900,1000]])

arr

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  10,   20,   30,   40,   50,   60,   70,   80,   90,  100],
       [ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000]])

In [11]:
arr[1:2,2:4]

array([[30, 40]])

In [12]:
arr=np.array([1,2,3])
print("Array:",arr)
print("Dimension",arr.ndim)
print("length of array",len(arr))
print("shape of array",arr.shape)


Array: [1 2 3]
Dimension 1
length of array 3
shape of array (3,)


In [13]:
#1.np.reshape()

arr=np.array([1,2,3,4])
print(f"Array: {arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Length of Array:{len(arr)}")
print(f"Shape of Array:{arr.shape}")
print(f"Reshape of Array:\n{arr.reshape(2,2)}")

Array: [1 2 3 4]
Dimension of Array:1
Length of Array:4
Shape of Array:(4,)
Reshape of Array:
[[1 2]
 [3 4]]


In [14]:
arr=np.array([1,2,3,4,5,6])
print(f"Array: {arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Length of Array:{len(arr)}")
print(f"Shape of Array:{arr.shape}")
print(f"Reshape of Array:\n{arr.reshape(3,2)}")

Array: [1 2 3 4 5 6]
Dimension of Array:1
Length of Array:6
Shape of Array:(6,)
Reshape of Array:
[[1 2]
 [3 4]
 [5 6]]


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Array: {arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Length of Array:{len(arr)}")
print(f"Shape of Array:{arr.shape}")
print("Reshape of Array:\n",arr.reshape(1,2,5))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Dimension of Array:1
Length of Array:10
Shape of Array:(10,)
Reshape of Array:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [16]:
arr = np.array([[1,2],[3,4]])
for i in arr:
    print("Elements in Array:",i)

Elements in Array: [1 2]
Elements in Array: [3 4]


In [17]:
arr = np.array([[1,2],[3,4]])
for i in arr:
    for j in i:
        print("Elements in Array:",j)

Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


In [18]:
#2.np.nditer()

arr = np.array([[1,2],[3,4]])
for i in  np.nditer(arr):
    print("Elements in Array",i)
    

Elements in Array 1
Elements in Array 2
Elements in Array 3
Elements in Array 4


In [19]:
a=np.nditer(arr)
a

In [20]:
next(a)

array(1)

In [21]:
#3.np.ndenumerate()

for i,j in enumerate(list("BYE")):
    print(i,j)

0 B
1 Y
2 E


In [22]:
arr = np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


In [23]:
arr = np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


In [24]:
#4.np.zeros()

np.zeros(3,int)

array([0, 0, 0])

In [25]:
arr = np.zeros((2,3), int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
#5.np.ones()

arr = np.ones(5, int)
arr

array([1, 1, 1, 1, 1])

In [27]:
#6.np.arange()

arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [28]:
arr = np.arange(1,2,2)
arr

array([1])

In [29]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr = np.arange(0,7,2)
arr

array([0, 2, 4, 6])

In [31]:
#7.linspace()

arr = np.linspace(1,10,num=10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
arr = np.linspace(2,11,num=11)
arr

array([ 2. ,  2.9,  3.8,  4.7,  5.6,  6.5,  7.4,  8.3,  9.2, 10.1, 11. ])

In [33]:
arr = np.linspace(2,4,num=10)
arr

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [34]:
#8.eye()

arr = np.eye(3,dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
arr = np.eye(3,2,dtype=int)
arr

array([[1, 0],
       [0, 1],
       [0, 0]])

In [36]:
arr = np.identity(4,int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [37]:
#9.identity()

arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [38]:
arr = np.identity(3, int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [39]:
#10.1 rand()

arr = np.random.rand(5)
arr

array([0.69941732, 0.40148101, 0.50871467, 0.88167125, 0.27010284])

In [40]:
arr = np.random.rand(5, 3)
arr

array([[0.43460263, 0.22235409, 0.50980539],
       [0.02406532, 0.97438467, 0.51023506],
       [0.85294201, 0.41060069, 0.76690143],
       [0.2717776 , 0.34516326, 0.880803  ],
       [0.34338254, 0.79385005, 0.10885516]])

In [41]:
#10.2 randint()

arr = np.random.randint(1,10,5)
arr

array([1, 3, 6, 9, 4])

In [42]:
arr = np.random.randint(1,10,(5,3))
arr


array([[9, 4, 9],
       [9, 1, 8],
       [3, 7, 9],
       [9, 2, 3],
       [9, 1, 9]])

In [43]:
#10.3 randn()

arr = np.random.randn(5)
arr

array([ 1.00107629, -0.62697148,  0.62375594, -0.76405433,  1.3306461 ])

In [44]:
arr = np.random.randn(5, 3)
arr

array([[ 1.93008899,  1.27475736,  0.7592051 ],
       [ 0.44484878, -0.0432562 ,  0.78272936],
       [ 0.47179213, -0.07880821, -0.37117457],
       [-1.14681157,  0.3018995 ,  0.14265711],
       [ 0.54121391,  0.29288909, -0.73737376]])

In [45]:
#10.4 ranf()

arr = np.random.ranf(3)
arr

array([0.66718005, 0.9703923 , 0.46310365])

In [46]:
#11.sort()

arr = np.random.randint(1,11,5)
arr

array([4, 1, 5, 1, 7])

In [47]:
np.sort(arr)

array([1, 1, 4, 5, 7])

In [48]:
arr = np.random.randint(1,10,(5,2))
arr

array([[4, 8],
       [6, 5],
       [5, 9],
       [3, 9],
       [3, 2]])

In [49]:
np.sort(arr,axis=0)

array([[3, 2],
       [3, 5],
       [4, 8],
       [5, 9],
       [6, 9]])

In [50]:
np.sort(arr,axis=1)

array([[4, 8],
       [5, 6],
       [5, 9],
       [3, 9],
       [2, 3]])

In [51]:
#12.append()

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,7])
new = np.append(arr1,arr2,axis=None)
new

array([1, 2, 3, 4, 5, 6, 7])

In [52]:
#13.ceil()

arr = np.array([1.5,2.5,3.5,4.5])
np.ceil(arr)


array([2., 3., 4., 5.])

In [53]:
#14.floor()

arr = np.array([1.5,2.5,3.5,4.5],int)
np.floor(arr)

array([1, 2, 3, 4])

In [54]:
#15.around()

arr = np.random.ranf(5)
arr

array([0.88596425, 0.93305902, 0.50626582, 0.89336246, 0.84382831])

In [55]:
print(np.around(arr,3))

[0.886 0.933 0.506 0.893 0.844]


In [56]:
#16.where()

str1 = "God Of The hell"
arr = np.array(list(str1))
print(arr)
np.where(arr=='h')

['G' 'o' 'd' ' ' 'O' 'f' ' ' 'T' 'h' 'e' ' ' 'h' 'e' 'l' 'l']


(array([ 8, 11]),)