In [ ]:
import numpy as np 

In [5]:
arr = np.array([1,23.45,'demon',11+11j])
print(type(arr))
arr

<class 'numpy.ndarray'>


array(['1', '23.45', 'demon', '(11+11j)'], dtype='<U64')

In [6]:
li=[1,2,3]
arr=np.array(li,dtype=float)
arr

array([1., 2., 3.])

In [7]:
li=[1,2,3]
arr=np.array(li,dtype=complex)
arr

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
li=[1.5,2.5,3.5]
arr=np.array(li,dtype=int)
arr

array([1, 2, 3])

In [9]:
li=[1.5,2.5,3.5]
arr=np.array(li,dtype=complex)
arr

array([1.5+0.j, 2.5+0.j, 3.5+0.j])

In [14]:
arr=np.array(100)
print("Array:",arr)
print("Dimension of Array:",arr.ndim)

Array: 100
Dimension of Array: 0


In [18]:
arr=np.array([1,2])
print("Array:",arr)
print("Dimension of Array:",arr.ndim)
print("dimension:",arr.shape)

Array: [1 2]
Dimension of Array: 1
dimension: (2,)


In [20]:
arr=np.array([[1,2,3,4,5,6,7,8,9,10],
            [10,20,30,40,50,60,70,80,90,100],
            [100,200,300,400,500,600,700,800,900,1000]])

arr

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  10,   20,   30,   40,   50,   60,   70,   80,   90,  100],
       [ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000]])

In [28]:
arr[1:2,2:4]

array([[30, 40]])

In [6]:
arr=np.array([1,2,3])
print("Array:",arr)
print("Dimension",arr.ndim)
print("length of array",len(arr))
print("shape of array",arr.shape)


Array: [1 2 3]
Dimension 1
length of array 3
shape of array (3,)


In [8]:
#1.np.reshape()

arr=np.array([1,2,3,4])
print(f"Array: {arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Length of Array:{len(arr)}")
print(f"Shape of Array:{arr.shape}")
print(f"Reshape of Array:\n{arr.reshape(2,2)}")

Array: [1 2 3 4]
Dimension of Array:1
Length of Array:4
Shape of Array:(4,)
Reshape of Array:
[[1 2]
 [3 4]]


In [9]:
arr=np.array([1,2,3,4,5,6])
print(f"Array: {arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Length of Array:{len(arr)}")
print(f"Shape of Array:{arr.shape}")
print(f"Reshape of Array:\n{arr.reshape(3,2)}")

Array: [1 2 3 4 5 6]
Dimension of Array:1
Length of Array:6
Shape of Array:(6,)
Reshape of Array:
[[1 2]
 [3 4]
 [5 6]]


In [15]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(f"Array: {arr}")
print(f"Dimension of Array:{arr.ndim}")
print(f"Length of Array:{len(arr)}")
print(f"Shape of Array:{arr.shape}")
print("Reshape of Array:\n",arr.reshape(1,2,5))

Array: [ 1  2  3  4  5  6  7  8  9 10]
Dimension of Array:1
Length of Array:10
Shape of Array:(10,)
Reshape of Array:
 [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [17]:
arr = np.array([[1,2],[3,4]])
for i in arr:
    print("Elements in Array:",i)

Elements in Array: [1 2]
Elements in Array: [3 4]


In [18]:
arr = np.array([[1,2],[3,4]])
for i in arr:
    for j in i:
        print("Elements in Array:",j)

Elements in Array: 1
Elements in Array: 2
Elements in Array: 3
Elements in Array: 4


In [19]:
#2.np.nditer()

arr = np.array([[1,2],[3,4]])
for i in  np.nditer(arr):
    print("Elements in Array",i)
    

Elements in Array 1
Elements in Array 2
Elements in Array 3
Elements in Array 4


In [21]:
a=np.nditer(arr)
a

In [22]:
next(a)

array(1)

In [26]:
#3.np.ndenumerate()

for i,j in enumerate(list("BYE")):
    print(i,j)

0 B
1 Y
2 E


In [27]:
arr = np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


In [28]:
arr = np.array(['B','Y','E'])
for i,j in np.ndenumerate(arr):
    print(i,j)

(0,) B
(1,) Y
(2,) E


In [29]:
#4.np.zeros()

np.zeros(3,int)

array([0, 0, 0])

In [30]:
arr = np.zeros((2,3), int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
#5.np.ones()

arr = np.ones(5, int)
arr

array([1, 1, 1, 1, 1])

In [33]:
#6.np.arange()

arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [35]:
arr = np.arange(1,2,2)
arr

array([1])

In [36]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr = np.arange(0,7,2)
arr

array([0, 2, 4, 6])

In [39]:
#7.linspace()

arr = np.linspace(1,10,num=10)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [40]:
arr = np.linspace(2,11,num=11)
arr

array([ 2. ,  2.9,  3.8,  4.7,  5.6,  6.5,  7.4,  8.3,  9.2, 10.1, 11. ])

In [46]:
arr = np.linspace(2,4,num=10)
arr

array([2.        , 2.22222222, 2.44444444, 2.66666667, 2.88888889,
       3.11111111, 3.33333333, 3.55555556, 3.77777778, 4.        ])

In [49]:
#8.eye()

arr = np.eye(3,dtype=int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
arr = np.eye(3,2,dtype=int)
arr

array([[1, 0],
       [0, 1],
       [0, 0]])

In [53]:
arr = np.identity(4,int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [3]:
#9.identity()

arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
arr = np.identity(3, int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [5]:
#10.1 rand()

arr = np.random.rand(5)
arr

array([0.07564181, 0.85194997, 0.02824197, 0.01881753, 0.16263469])

In [9]:
arr = np.random.rand(5, 3)
arr

array([[0.24772165, 0.55450189, 0.62598015],
       [0.74412141, 0.59071598, 0.05055042],
       [0.02046538, 0.94880883, 0.75552432],
       [0.71022077, 0.89599595, 0.50154574],
       [0.98896323, 0.58798867, 0.37362309]])

In [10]:
#10.2 randint()

arr = np.random.randint(1,10,5)
arr

array([6, 5, 7, 2, 1], dtype=int32)

In [12]:
arr = np.random.randint(1,10,(5,3))
arr


array([[7, 8, 6],
       [7, 3, 4],
       [1, 1, 5],
       [5, 5, 7],
       [9, 1, 4]], dtype=int32)

In [14]:
#10.3 randn()

arr = np.random.randn(5)
arr

array([ 1.08571769,  0.33967634, -0.63375543, -0.25286775,  1.36521328])

In [15]:
arr = np.random.randn(5, 3)
arr

array([[ 1.27922709,  0.6045779 , -0.70817936],
       [ 0.70373961,  0.16521458, -1.16662277],
       [ 0.19978501, -0.20929575, -0.30979431],
       [-0.33685481, -1.52378158,  1.68600253],
       [-0.83814088, -0.14838909,  0.24279994]])

In [16]:
#10.4 ranf()

arr = np.random.ranf(3)
arr

array([0.05290557, 0.91129097, 0.31124757])

In [20]:
#11.sort()

arr = np.random.randint(1,11,5)
arr

array([ 5, 10,  8,  9,  5], dtype=int32)

In [21]:
np.sort(arr)

array([ 5,  5,  8,  9, 10], dtype=int32)

In [23]:
arr = np.random.randint(1,10,(5,2))
arr

array([[7, 3],
       [5, 4],
       [2, 1],
       [1, 7],
       [5, 2]], dtype=int32)

In [24]:
np.sort(arr,axis=0)

array([[1, 1],
       [2, 2],
       [5, 3],
       [5, 4],
       [7, 7]], dtype=int32)

In [25]:
np.sort(arr,axis=1)

array([[3, 7],
       [4, 5],
       [1, 2],
       [1, 7],
       [2, 5]], dtype=int32)

In [27]:
#12.append()

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6,7])
new = np.append(arr1,arr2,axis=None)
new

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#13.ceil()

arr = np.array([1.5,2.5,3.5,4.5])
np.ceil(arr)


array([2., 3., 4., 5.])

In [30]:
#14.floor()

arr = np.array([1.5,2.5,3.5,4.5],int)
np.floor(arr)

array([1, 2, 3, 4])

In [32]:
#15.around()

arr = np.random.ranf(5)
arr

array([0.7118024 , 0.77810218, 0.55247652, 0.41976035, 0.07739072])

In [33]:
print(np.around(arr,3))

[0.712 0.778 0.552 0.42  0.077]


In [35]:
#16.where()

str1 = "God Of The hell"
arr = np.array(list(str1))
print(arr)
np.where(arr=='h')

['G' 'o' 'd' ' ' 'O' 'f' ' ' 'T' 'h' 'e' ' ' 'h' 'e' 'l' 'l']


(array([ 8, 11]),)

: 