# Tensorflow Functions:

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.18.0


In [3]:
a = tf.constant(5)
b = tf.constant([1, 2, 3, 4, 5])

print(a)
print(b)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
x = tf.constant(11.43)
y = tf.constant(7.61)

add = tf.add(x, y)  
sub = tf.subtract(x, y)  
mul = tf.multiply(x, y)  
div = tf.divide(x, y)  

print(f"Addition: {add}, Subtraction: {sub}, Multiplication: {mul}, Division: {div}")


Addition: 19.040000915527344, Subtraction: 3.820000171661377, Multiplication: 86.98230743408203, Division: 1.5019711256027222


In [6]:
var = tf.Variable([1, 2, 3, 4])
var.assign([5, 6, 7, 8])  
print(var)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([5, 6, 7, 8], dtype=int32)>


In [7]:
import numpy as np

arr = np.array([1, 2, 3])
tensor = tf.convert_to_tensor(arr)
print(tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [8]:
x = tf.constant([1.7, 2.3, 3.9], dtype=tf.float32)
y = tf.cast(x, dtype=tf.int32)
print(y)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [9]:
tensor = tf.constant([[1, 2, 3], [4, 5, 6]])
print(tf.shape(tensor))

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [10]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
y = tf.reshape(x, [2, 3])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [14]:
zeros_tensor = tf.zeros([3, 3], tf.int32)
print(zeros_tensor)

tf.Tensor(
[[0 0 0]
 [0 0 0]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [16]:
random_tensor = tf.random.uniform([3, 3], minval=0, maxval=10, dtype=tf.int32)
print(random_tensor)

tf.Tensor(
[[9 1 1]
 [3 6 8]
 [4 7 5]], shape=(3, 3), dtype=int32)


In [17]:
random_tensor = tf.random.normal([2, 2], mean=0, stddev=1)
print(random_tensor)

tf.Tensor(
[[-1.8543863   0.22732791]
 [ 0.32256186 -0.9669885 ]], shape=(2, 2), dtype=float32)


In [18]:
x = tf.constant([1, 2, 3])
y = tf.constant([4, 5, 6])
result = tf.add(x, y)
print(result)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [19]:
tensor = tf.constant([[1, 2], [3, 4]])
sum_result = tf.reduce_sum(tensor)
print(sum_result)

tf.Tensor(10, shape=(), dtype=int32)


In [20]:
mean_result = tf.reduce_mean(tensor)
print(mean_result)

tf.Tensor(2, shape=(), dtype=int32)


In [21]:
tensor = tf.constant([10, 20, 30, 40])
index = tf.argmax(tensor)
print(index)

tf.Tensor(3, shape=(), dtype=int64)
